<?php


namespace ZoranWong\LaraEventQueue\Queue;


use Illuminate\Queue\RedisQueue;

class ReliableRedisQueue extends RedisQueue
{
    protected $job = null;

    public function ack()
    {
        $this->getConnection()->subscribe('', function () {

        });
    }

    public function nack()
    {

    }

    public function pop($queue = null)
    {
        $this->job = parent::pop($queue); // TODO: Change the autogenerated stub
        return $this->job;
    }

    public function push($job, $data = '', $queue = null)
    {
        return parent::push($job, $data, $queue); // TODO: Change the autogenerated stub
    }

    public function later($delay, $job, $data = '', $queue = null)
    {
        return parent::later($delay, $job, $data, $queue); // TODO: Change the autogenerated stub
    }

    public function bulk($jobs, $data = '', $queue = null)
    {
        parent::bulk($jobs, $data, $queue); // TODO: Change the autogenerated stub
    }


}
