<?php


namespace ZoranWong\LaraEventQueue;

use Illuminate\Queue\Worker;
use Illuminate\Queue\WorkerOptions;
use Illuminate\Support\Facades\Redis;
use Predis\ClientInterface;
use ZoranWong\LaraEventQueue\Jobs\OrderJobInterface;
use ZoranWong\LaraEventQueue\Jobs\ReliableJobInterface;

class EventQueueWorker extends Worker
{
    /**@var ClientInterface */
    protected $redis = null;

    /**
     *保证job多进程下可以有序执行
     * @param ReliableJobInterface $job
     * @param $connectionName
     * @param WorkerOptions $options
     */
    protected function runJob($job, $connectionName, WorkerOptions $options)
    {
        if ($job instanceof OrderJobInterface) {
            if (!$job->canRun()) {
                $job->nack();
            } elseif ($job->lock()) {
                parent::runJob($job, $connectionName, $options); // TODO: Change the autogenerated stub
                $job->unlock();
                $job->popUUId();
            } else {
                $job->nack();
            }
        } else {
            parent::runJob($job, $connectionName, $options); // TODO: Change the autogenerated stub
        }
    }
}
