<?php


namespace ZoranWong\LaraEventQueue;

use Illuminate\Queue\QueueManager;
use Illuminate\Queue\QueueServiceProvider;
use ZoranWong\LaraEventQueue\Connectors\ReliableRedisConnector;

class LaraEventQueueServiceProvider extends QueueServiceProvider
{

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->singleton('reliable.queue.cache', function () {
            return $this->app->make('cache')->store('');
        });
    }

    /**
     * Register the connectors on the queue manager.
     *
     * @param  QueueManager  $manager
     * @return void
     */
    public function registerConnectors($manager)
    {
        foreach (['Null', 'Sync', 'Database', 'Redis', 'Beanstalkd', 'Sqs', 'ReliableRedis'] as $connector) {
            $this->{"register{$connector}Connector"}($manager);
        }
    }
    /**
     * Register the Redis queue connector.
     *
     * @param  QueueManager  $manager
     * @return void
     */
    protected function registerReliableRedisConnector($manager)
    {
        $manager->addConnector('reliable-redis', function () {
            return new ReliableRedisConnector($this->app['redis']);
        });
    }
}
